# Generated by Django 5.2 on 2025-04-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="content_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="content_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="title_uz",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="content_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="content_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_uz",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="description_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="name_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="partner",
            name="name_uz",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_uz",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="bio_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="bio_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="bio_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="name_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="name_uz",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
