# Generated by Django 5.2 on 2025-05-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_article_options_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_en",
            field=models.TextField(null=True, verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_ru",
            field=models.TextField(null=True, verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_uz",
            field=models.TextField(null=True, verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="articles/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title_uz",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="map_coordinates",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Координаты карты"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(max_length=100, verbose_name="Телефон"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="working_hours",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Рабочие часы"
            ),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Прочитано"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="message",
            field=models.TextField(verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(max_length=255, verbose_name="Тема"),
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="news",
            name="content_en",
            field=models.TextField(null=True, verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="news",
            name="content_ru",
            field=models.TextField(null=True, verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="news",
            name="content_uz",
            field=models.TextField(null=True, verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="news/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_uz",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="description_ru",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="description_uz",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="logo",
            field=models.ImageField(upload_to="partners/", verbose_name="Логотип"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="name_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="name_uz",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="partner",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Сайт"),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="products/", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="Доступность"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новинка"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_uz",
            field=models.CharField(max_length=200, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, unique=True, verbose_name="Ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="bio",
            field=models.TextField(verbose_name="Биография"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="bio_en",
            field=models.TextField(null=True, verbose_name="Биография"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="bio_ru",
            field=models.TextField(null=True, verbose_name="Биография"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="bio_uz",
            field=models.TextField(null=True, verbose_name="Биография"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="name_en",
            field=models.CharField(max_length=200, null=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="name_ru",
            field=models.CharField(max_length=200, null=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="name_uz",
            field=models.CharField(max_length=200, null=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(upload_to="team/", verbose_name="Фотография"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="position",
            field=models.CharField(
                choices=[
                    ("CEO", "CEO"),
                    ("CTO", "CTO"),
                    ("CFO", "CFO"),
                    ("COO", "COO"),
                    ("Manager", "Manager"),
                    ("Specialist", "Specialist"),
                    ("Other", "Other"),
                ],
                max_length=100,
                verbose_name="Должность",
            ),
        ),
    ]
